var namespacedvblinkremote =
[
    [ "IDVBLinkRemoteConnection", "classdvblinkremote_1_1_i_d_v_b_link_remote_connection.html", "classdvblinkremote_1_1_i_d_v_b_link_remote_connection" ],
    [ "DVBLinkRemote", "classdvblinkremote_1_1_d_v_b_link_remote.html", "classdvblinkremote_1_1_d_v_b_link_remote" ],
    [ "Request", "classdvblinkremote_1_1_request.html", null ],
    [ "GetChannelsRequest", "classdvblinkremote_1_1_get_channels_request.html", "classdvblinkremote_1_1_get_channels_request" ],
    [ "ChannelIdentifierList", "classdvblinkremote_1_1_channel_identifier_list.html", "classdvblinkremote_1_1_channel_identifier_list" ],
    [ "EpgSearchRequest", "classdvblinkremote_1_1_epg_search_request.html", "classdvblinkremote_1_1_epg_search_request" ],
    [ "StreamRequest", "classdvblinkremote_1_1_stream_request.html", "classdvblinkremote_1_1_stream_request" ],
    [ "TranscodingOptions", "classdvblinkremote_1_1_transcoding_options.html", "classdvblinkremote_1_1_transcoding_options" ],
    [ "TranscodedVideoStreamRequest", "classdvblinkremote_1_1_transcoded_video_stream_request.html", "classdvblinkremote_1_1_transcoded_video_stream_request" ],
    [ "RealTimeTransportProtocolStreamRequest", "classdvblinkremote_1_1_real_time_transport_protocol_stream_request.html", "classdvblinkremote_1_1_real_time_transport_protocol_stream_request" ],
    [ "HttpLiveStreamRequest", "classdvblinkremote_1_1_http_live_stream_request.html", "classdvblinkremote_1_1_http_live_stream_request" ],
    [ "WindowsMediaStreamRequest", "classdvblinkremote_1_1_windows_media_stream_request.html", "classdvblinkremote_1_1_windows_media_stream_request" ],
    [ "RawHttpStreamRequest", "classdvblinkremote_1_1_raw_http_stream_request.html", "classdvblinkremote_1_1_raw_http_stream_request" ],
    [ "RawUdpStreamRequest", "classdvblinkremote_1_1_raw_udp_stream_request.html", "classdvblinkremote_1_1_raw_udp_stream_request" ],
    [ "StopStreamRequest", "classdvblinkremote_1_1_stop_stream_request.html", "classdvblinkremote_1_1_stop_stream_request" ],
    [ "AddScheduleRequest", "classdvblinkremote_1_1_add_schedule_request.html", "classdvblinkremote_1_1_add_schedule_request" ],
    [ "AddManualScheduleRequest", "classdvblinkremote_1_1_add_manual_schedule_request.html", "classdvblinkremote_1_1_add_manual_schedule_request" ],
    [ "AddScheduleByEpgRequest", "classdvblinkremote_1_1_add_schedule_by_epg_request.html", "classdvblinkremote_1_1_add_schedule_by_epg_request" ],
    [ "GetRecordingsRequest", "classdvblinkremote_1_1_get_recordings_request.html", "classdvblinkremote_1_1_get_recordings_request" ],
    [ "RemoveScheduleRequest", "classdvblinkremote_1_1_remove_schedule_request.html", "classdvblinkremote_1_1_remove_schedule_request" ],
    [ "RemoveRecordingRequest", "classdvblinkremote_1_1_remove_recording_request.html", "classdvblinkremote_1_1_remove_recording_request" ],
    [ "GetParentalStatusRequest", "classdvblinkremote_1_1_get_parental_status_request.html", "classdvblinkremote_1_1_get_parental_status_request" ],
    [ "SetParentalLockRequest", "classdvblinkremote_1_1_set_parental_lock_request.html", "classdvblinkremote_1_1_set_parental_lock_request" ],
    [ "Response", "classdvblinkremote_1_1_response.html", null ],
    [ "Channel", "classdvblinkremote_1_1_channel.html", "classdvblinkremote_1_1_channel" ],
    [ "ChannelList", "classdvblinkremote_1_1_channel_list.html", "classdvblinkremote_1_1_channel_list" ],
    [ "Program", "classdvblinkremote_1_1_program.html", "classdvblinkremote_1_1_program" ],
    [ "EpgData", "classdvblinkremote_1_1_epg_data.html", "classdvblinkremote_1_1_epg_data" ],
    [ "ChannelEpgData", "classdvblinkremote_1_1_channel_epg_data.html", "classdvblinkremote_1_1_channel_epg_data" ],
    [ "EpgSearchResult", "classdvblinkremote_1_1_epg_search_result.html", "classdvblinkremote_1_1_epg_search_result" ],
    [ "Stream", "classdvblinkremote_1_1_stream.html", "classdvblinkremote_1_1_stream" ],
    [ "Recording", "classdvblinkremote_1_1_recording.html", "classdvblinkremote_1_1_recording" ],
    [ "RecordingList", "classdvblinkremote_1_1_recording_list.html", "classdvblinkremote_1_1_recording_list" ],
    [ "ParentalStatus", "classdvblinkremote_1_1_parental_status.html", "classdvblinkremote_1_1_parental_status" ]
];